// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Palindrome.Api.Data.Context;

#nullable disable

namespace Palindrome.Api.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20221102171515_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Palindrome.Api.Models.PalindromeResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreateAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPalindrome")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Palindromes");
                });
#pragma warning restore 612, 618
        }
    }
}
